name: webview_flutter_example
description: Demonstrates how to use the webview_flutter plugin.
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.6
  http: 0.13.6
  flutter_webview_pro: ^3.0.1+4
  # flutter_webview_pro:
  #   git:
  #     url: https://github.com/wenzhiming/flutter-plugins.git
  #     ref: dev-3.0.4
  #     path: packages/webview_flutter/webview_flutter

dev_dependencies:
  build_runner: ^2.1.5
  espresso: ^0.2.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  webview_flutter_platform_interface: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_audio.ogg
    - assets/sample_video.mp4
    - assets/www/index.html
    - assets/www/styles/style.css
